---
# This playbook will configure all miners

# Verifies that python is installed
- include: roles/python/tasks/main.yml

# Set FQDN
- hosts: all
  roles:
    - role: hostname

# Common Ubuntu stuff
- hosts: all
  roles:
    - role: ubuntu-common

# Docker
- hosts: all
  roles:
    - role: docker

# Configure AMD GPU
- hosts: amdgpu
  roles:
    - role: amdgpu

# Configure Nvidia GPU
- hosts: nvidiagpu
  roles:
    - role: nvidiagpu

# Join Rancher2 server
- hosts: rancher2
  roles:
    - role: rancher2
