---
# This playbook cleans up all miners and removes all services

- name: sudo
  become: yes
  template:
    src: "90-wes.sudo"
    dest: "/etc/sudoers.d/90-wes"

- name: Setup wes local user
  become: yes
  user:
    name: wes
    password: "{{ wes_crypted_pwd }}"

- name: Add authorized key
  become: true
  authorized_key:
    user: wes
    state: present
    key: '{{ item }}'
  with_file: 
    - public-keys/wes

- name: Fix sshd for X11
  become: yes
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^AddressFamily '
    line: 'AddressFamily inet'
  register: sshd_changes

- name: Restart sshd
  become: yes
  service:
    name: sshd
    state: restarted
    enabled: yes
  when: sshd_changes.changed

#- name: Setup apt repositories
#  become: yes
#  apt_repository:
#    repo: "{{ item }}"
#    state: present
#    update_cache: no
#  with_items:
#     -  "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} main restricted"
#     -  "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }}-updates main restricted"
#     -  "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe"
#     -  "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }}-updates universe"
#     -  "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} multiverse"
#     -  "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }}-updates multiverse"
#     -  "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }}-backports main restricted universe multiverse"
#     -  "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }}-security main restricted"
#     -  "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }}-security universe"
#     -  "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }}-security multiverse"

#- name: Add apt key
#  become: yes
#  apt_key:
#    data: "{{ lookup('file', 'public-keys/D3F1E2F6-public.key') }}"
#    state: present
#  when: not maas

#- name: Remove sources.list (using sources.list.d intead)
#  become: yes
#  file:
#    path: /etc/apt/sources.list
#    state: absent
#  register: removed_sources_list

#- name: Setup apt repositories
#  become: yes
#  apt_repository:
#    repo: "{{ item }}"
#    state: present
#    update_cache: no
#  with_items:
#     - "deb https://nexus.elastiscale.net/repository/ubuntu-archive-{{ ansible_distribution_release }}/ {{ ansible_distribution_release }} main restricted"
#     - "deb https://nexus.elastiscale.net/repository/ubuntu-archive-{{ ansible_distribution_release }}/ {{ ansible_distribution_release }}-updates main restricted"
#     - "deb https://nexus.elastiscale.net/repository/ubuntu-archive-{{ ansible_distribution_release }}/ {{ ansible_distribution_release }} universe"
#     - "deb https://nexus.elastiscale.net/repository/ubuntu-archive-{{ ansible_distribution_release }}/ {{ ansible_distribution_release }}-updates universe"
#     - "deb https://nexus.elastiscale.net/repository/ubuntu-archive-{{ ansible_distribution_release }}/ {{ ansible_distribution_release }} multiverse"
#     - "deb https://nexus.elastiscale.net/repository/ubuntu-archive-{{ ansible_distribution_release }}/ {{ ansible_distribution_release }}-updates multiverse"
#     - "deb https://nexus.elastiscale.net/repository/ubuntu-archive-{{ ansible_distribution_release }}/ {{ ansible_distribution_release }}-backports main restricted universe multiverse"
#     - "deb https://nexus.elastiscale.net/repository/ubuntu-security-{{ ansible_distribution_release }}/ {{ ansible_distribution_release }}-security main restricted"
#     - "deb https://nexus.elastiscale.net/repository/ubuntu-security-{{ ansible_distribution_release }}/ {{ ansible_distribution_release }}-security universe"
#     - "deb https://nexus.elastiscale.net/repository/ubuntu-security-{{ ansible_distribution_release }}/ {{ ansible_distribution_release }}-security multiverse"
##     - "deb https://nexus.elastiscale.net/repository/ubuntu-{{ ansible_distribution_release }}-custom/ {{ ansible_distribution_release }} main restricted"
#  when: not maas
#  register: apt_repos_updated

#- name: Remove old local apt repositories if necessary
#  become: yes
#  apt_repository:
#    repo: "{{ item }}"
#    state: absent
#    update_cache: no
#  with_items:
#     - "deb https://nexus.cowtownt.org/repository/ubuntu-archive-{{ ansible_distribution_release }}/ {{ ansible_distribution_release }} main restricted"
#     - "deb https://nexus.cowtownt.org/repository/ubuntu-archive-{{ ansible_distribution_release }}/ {{ ansible_distribution_release }}-updates main restricted"
#     - "deb https://nexus.cowtownt.org/repository/ubuntu-archive-{{ ansible_distribution_release }}/ {{ ansible_distribution_release }} universe"
#     - "deb https://nexus.cowtownt.org/repository/ubuntu-archive-{{ ansible_distribution_release }}/ {{ ansible_distribution_release }}-updates universe"
#     - "deb https://nexus.cowtownt.org/repository/ubuntu-archive-{{ ansible_distribution_release }}/ {{ ansible_distribution_release }} multiverse"
#     - "deb https://nexus.cowtownt.org/repository/ubuntu-archive-{{ ansible_distribution_release }}/ {{ ansible_distribution_release }}-updates multiverse"
#     - "deb https://nexus.cowtownt.org/repository/ubuntu-archive-{{ ansible_distribution_release }}/ {{ ansible_distribution_release }}-backports main restricted universe multiverse"
#     - "deb https://nexus.cowtownt.org/repository/ubuntu-security-{{ ansible_distribution_release }}/ {{ ansible_distribution_release }}-security main restricted"
#     - "deb https://nexus.cowtownt.org/repository/ubuntu-security-{{ ansible_distribution_release }}/ {{ ansible_distribution_release }}-security universe"
#     - "deb https://nexus.cowtownt.org/repository/ubuntu-security-{{ ansible_distribution_release }}/ {{ ansible_distribution_release }}-security multiverse"
##     - "deb https://nexus.elastiscale.net/repository/ubuntu-{{ ansible_distribution_release }}-custom/ {{ ansible_distribution_release }} main restricted"
#  register: apt_repos_updated

#- name: Clear old apt lists
#  become: yes
#  command: mv /etc/apt/sources.list /etc/apt/sources.list.orig
#  when: apt_repos_updated.changed
#
#- name: Setup apt repositories
#  become: yes
#  apt:
#    update_cache: yes
#  when: not maas and apt_repos_updated.changed
#
#- name: Delete internet apt repositories
#  become: yes
#  apt_repository:
#    repo: "{{ item }}"
#    state: absent
#  with_items:
#    - "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} main restricted"
#    - "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates main restricted"
#    - "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
#    - "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates universe"
#    - "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} multiverse"
#    - "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates multiverse"
#    - "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-backports main restricted universe multiverse"
#    - "deb http://security.ubuntu.com/ubuntu {{ ansible_distribution_release }}-security main restricted"
#    - "deb http://security.ubuntu.com/ubuntu {{ ansible_distribution_release }}-security universe"
#    - "deb http://security.ubuntu.com/ubuntu {{ ansible_distribution_release }}-security multiverse"
#  when: not maas

- name: Set kernel.panic in sysctl.conf
  become: yes
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^kernel.panic ='
    line: 'kernel.panic = 10'
  register: sysctl

- name: Reload sysctl settings
  become: yes
  command: sysctl -p
  when: sysctl.changed

- name: Install nfs-common
  become: yes
  apt:
    name: nfs-common

# python-routes is for ceph dashboard
- name: Install python-routes
  become: yes
  apt:
    name: python-routes
  
- name: Setup NFS home dir
  become: yes
  mount:
    path: /home/wes
    src: 172.16.1.17:/mnt/raid5_kdrive/home/wes
    fstype: nfs
    state: mounted
  when: location == "weshouse"

- name: Setup jamiehouse home dir
  become: yes
  mount:
    path: "{{ home_dir[location]['path'] }}"
    src: "{{ home_dir[location]['src'] }}"
    fstype: "{{ home_dir[location]['fstype'] }}"
    opts: "{{ home_dir[location]['opts'] }}"
    state: mounted
  when: location == "jamiehouse"

- name: Create /mnt/raid5_kdrive dir
  become: yes
  file:
    path: /mnt/raid5_kdrive
    state: directory
  when: location == "weshouse"

- name: Setup NFS raid5_kdrive dir
  become: yes
  mount:
    path: /mnt/raid5_kdrive
    src: 172.16.1.17:/mnt/raid5_kdrive/
    fstype: nfs
    state: mounted
  when: location == "weshouse"

- name: Install chrony
  become: yes
  apt:
    name: chrony

- name: Enable chrony
  become: yes
  systemd:
    enabled: yes
    name: chrony

- name: Start chrony
  become: yes
  systemd:
    state: started
    name: chrony

# Configure page-up page-down history
- name: Configure page-up history
  become: yes
  lineinfile:
    path: /etc/inputrc
    regexp: 'history-search-forward'
    line: '"\e[6~": history-search-forward'

- name: Configure page-down history
  become: yes
  lineinfile:
    path: /etc/inputrc
    regexp: 'history-search-backward'
    line: '"\e[5~": history-search-backward'

- name: Add modprobe rbd
  become: yes
  lineinfile:
    path: /etc/modules
    line: "rbd"

- name: Modprobe rbd
  become: true
  modprobe:
    name: rbd
    state: present

- name: Stop and disable systemd-resolved
  become: true
  systemd:
    name: systemd-resolved
    enabled: no
    state: stopped
