---
# This playbook cleans up all miners and removes all services

- name: sudo
  become: yes
  template:
    src: "90-wes.sudo"
    dest: "/etc/sudoers.d/90-wes"

- name: Add authorized key
  authorized_key:
    user: wes
    state: present
    key: '{{ item }}'
  with_file: 
    - public-keys/wes

- name: Add apt key
  become: yes
  apt_key:
    data: "{{ lookup('file', 'public-keys/D3F1E2F6-public.key') }}"
    state: present

- name: Setup apt repositories
  become: yes
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
     - "deb https://nexus.cowtownt.org/repository/ubuntu-archive-xenial/ xenial main restricted"
     - "deb https://nexus.cowtownt.org/repository/ubuntu-archive-xenial/ xenial-updates main restricted"
     - "deb https://nexus.cowtownt.org/repository/ubuntu-archive-xenial/ xenial universe"
     - "deb https://nexus.cowtownt.org/repository/ubuntu-archive-xenial/ xenial-updates universe"
     - "deb https://nexus.cowtownt.org/repository/ubuntu-archive-xenial/ xenial multiverse"
     - "deb https://nexus.cowtownt.org/repository/ubuntu-archive-xenial/ xenial-updates multiverse"
     - "deb https://nexus.cowtownt.org/repository/ubuntu-archive-xenial/ xenial-backports main restricted universe multiverse"
     - "deb https://nexus.cowtownt.org/repository/ubuntu-security-xenial/ xenial-security main restricted"
     - "deb https://nexus.cowtownt.org/repository/ubuntu-security-xenial/ xenial-security universe"
     - "deb https://nexus.cowtownt.org/repository/ubuntu-security-xenial/ xenial-security multiverse"
     - "deb https://nexus.cowtownt.org/repository/ubuntu-xenial-custom/ xenial main restricted"

- name: Delete internet apt repositories
  become: yes
  apt_repository:
    repo: "{{ item }}"
    state: absent
  with_items:
    - "deb http://us.archive.ubuntu.com/ubuntu/ xenial main restricted"
    - "deb http://us.archive.ubuntu.com/ubuntu/ xenial-updates main restricted"
    - "deb http://us.archive.ubuntu.com/ubuntu/ xenial universe"
    - "deb http://us.archive.ubuntu.com/ubuntu/ xenial-updates universe"
    - "deb http://us.archive.ubuntu.com/ubuntu/ xenial multiverse"
    - "deb http://us.archive.ubuntu.com/ubuntu/ xenial-updates multiverse"
    - "deb http://us.archive.ubuntu.com/ubuntu/ xenial-backports main restricted universe multiverse"
    - "deb http://security.ubuntu.com/ubuntu xenial-security main restricted"
    - "deb http://security.ubuntu.com/ubuntu xenial-security universe"
    - "deb http://security.ubuntu.com/ubuntu xenial-security multiverse"

- name: Set kernel.panic in sysctl.conf
  become: yes
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^kernel.panic ='
    line: 'kernel.panic = 10'
  register: sysctl

- name: Reload sysctl settings
  become: yes
  command: sysctl -p
  when: sysctl.changed
  
