---
# This playbook cleans up all miners and removes all services

- name: sudo
  become: yes
  template:
    src: "90-wes.sudo"
    dest: "/etc/sudoers.d/90-wes"

- name: Add authorized key
  become: true
  authorized_key:
    user: wes
    state: present
    key: '{{ item }}'
  with_file: 
    - public-keys/wes

- name: Add apt key
  become: yes
  apt_key:
    data: "{{ lookup('file', 'public-keys/D3F1E2F6-public.key') }}"
    state: present
  when: not maas

- name: Setup apt repositories
  become: yes
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: no
  with_items:
     - "deb https://nexus.cowtownt.org/repository/ubuntu-archive-{{ ansible_distribution_release }}/ {{ ansible_distribution_release }} main restricted"
     - "deb https://nexus.cowtownt.org/repository/ubuntu-archive-{{ ansible_distribution_release }}/ {{ ansible_distribution_release }}-updates main restricted"
     - "deb https://nexus.cowtownt.org/repository/ubuntu-archive-{{ ansible_distribution_release }}/ {{ ansible_distribution_release }} universe"
     - "deb https://nexus.cowtownt.org/repository/ubuntu-archive-{{ ansible_distribution_release }}/ {{ ansible_distribution_release }}-updates universe"
     - "deb https://nexus.cowtownt.org/repository/ubuntu-archive-{{ ansible_distribution_release }}/ {{ ansible_distribution_release }} multiverse"
     - "deb https://nexus.cowtownt.org/repository/ubuntu-archive-{{ ansible_distribution_release }}/ {{ ansible_distribution_release }}-updates multiverse"
     - "deb https://nexus.cowtownt.org/repository/ubuntu-archive-{{ ansible_distribution_release }}/ {{ ansible_distribution_release }}-backports main restricted universe multiverse"
     - "deb https://nexus.cowtownt.org/repository/ubuntu-security-{{ ansible_distribution_release }}/ {{ ansible_distribution_release }}-security main restricted"
     - "deb https://nexus.cowtownt.org/repository/ubuntu-security-{{ ansible_distribution_release }}/ {{ ansible_distribution_release }}-security universe"
     - "deb https://nexus.cowtownt.org/repository/ubuntu-security-{{ ansible_distribution_release }}/ {{ ansible_distribution_release }}-security multiverse"
#     - "deb https://nexus.cowtownt.org/repository/ubuntu-{{ ansible_distribution_release }}-custom/ {{ ansible_distribution_release }} main restricted"
  when: not maas
  register: apt_repos_updated

- name: Setup apt repositories
  become: yes
  apt:
    update_cache: yes
  when: not maas and apt_repos_updated.changed

- name: Delete internet apt repositories
  become: yes
  apt_repository:
    repo: "{{ item }}"
    state: absent
  with_items:
    - "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} main restricted"
    - "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates main restricted"
    - "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
    - "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates universe"
    - "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} multiverse"
    - "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates multiverse"
    - "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-backports main restricted universe multiverse"
    - "deb http://security.ubuntu.com/ubuntu {{ ansible_distribution_release }}-security main restricted"
    - "deb http://security.ubuntu.com/ubuntu {{ ansible_distribution_release }}-security universe"
    - "deb http://security.ubuntu.com/ubuntu {{ ansible_distribution_release }}-security multiverse"
  when: not maas

- name: Set kernel.panic in sysctl.conf
  become: yes
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^kernel.panic ='
    line: 'kernel.panic = 10'
  register: sysctl

- name: Reload sysctl settings
  become: yes
  command: sysctl -p
  when: sysctl.changed

- name: Install nfs-common
  become: yes
  apt:
    name: nfs-common
  
- name: Setup NFS home dir
  become: yes
  mount:
    path: /home/wes
    src: 172.16.1.17:/mnt/raid5_kdrive/home/wes
    fstype: nfs
    state: mounted
  when: location == "weshouse"

- name: Create /mnt/raid5_kdrive dir
  become: yes
  file:
    path: /mnt/raid5_kdrive
    state: directory
  when: location == "weshouse"

- name: Setup NFS raid5_kdrive dir
  become: yes
  mount:
    path: /mnt/raid5_kdrive
    src: 172.16.1.17:/mnt/raid5_kdrive/
    fstype: nfs
    state: mounted
  when: location == "weshouse"

- name: Install ntp
  become: yes
  apt:
    name: ntp

- name: Enable NTP
  become: yes
  systemd:
    enabled: yes
    name: ntp

- name: Start NTP
  become: yes
  systemd:
    state: started
    name: ntp

# Configure page-up page-down history
- name: Configure page-up history
  become: yes
  lineinfile:
    path: /etc/inputrc
    regexp: 'history-search-forward'
    line: '"\e[6~": history-search-forward'

- name: Configure page-down history
  become: yes
  lineinfile:
    path: /etc/inputrc
    regexp: 'history-search-backward'
    line: '"\e[5~": history-search-backward'

- name: Add modprobe rbd
  become: yes
  lineinfile:
    path: /etc/modules
    line: "rbd"

- name: Modprobe rbd
  become: true
  modprobe:
    name: rbd
    state: present
