# Install AMD gpu and upgrade kernel

#- name: Update all packages to the latest version
#  apt:
#    upgrade: dist

- name: Add nvidia-docker2 apt key
  become: yes
  apt_key:
    url: "https://nvidia.github.io/nvidia-docker/gpgkey"
    state: present

#- name: Setup nvidia-docker2 apt repositories
#  become: yes
#  template:
#    src: "templates/{{ item }}"
#    dest: "/etc/apt/sources.list.d/{{ item }}"
#  loop: "{{ nvidia_docker_repos[location] }}"
#    #with_items:
#          #    - "nvidia-docker.list"

- name: Setup nvidia-docker2 apt repositories
  become: yes
  apt_repository:
    repo: "{{ item }}"
    state: present
  loop: "{{ nvidia_docker_repos[location] }}"

- name: Install nvidia-docker2
  become: yes
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - "nvidia-docker2"
    - "nvidia-384"
#    - "cuda-drivers"

- name: Deploy daemon.json
  become: yes
  template:
    src: templates/daemon.json
    dest: /etc/docker/daemon.json
  register: daemonjson

- name: Restart docker
  become: yes
  service:
    name: docker
    state: restarted
    enabled: yes
  when: daemonjson.changed

