# Install AMD gpu and upgrade kernel

#- name: Update all packages to the latest version
#  apt:
#    upgrade: dist

- name: Add nvidia-docker2 apt key
  become: yes
  apt_key:
    url: "https://nvidia.github.io/nvidia-docker/gpgkey"
    state: present
  with_items:
    - "https://nvidia.github.io/nvidia-docker/gpgkey"
    - "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    - "https://nvidia.github.io/kubernetes/gpgkey"

- name: Setup nvidia-docker2 apt repositories
  become: yes
  template:
    src: "templates/{{ item }}"
    dest: "/etc/apt/sources.list.d/{{ item }}"
  with_items:
    - "nvidia-docker.list"
    - "nvidia-kubernetes.list"

- name: Install nvidia-docker2
  become: yes
  apt:
    name: nvidia-docker2
    update_cache: yes
  with_items:
    - "nvidia-docker2"
    - "kubectl=1.9.7+nvidia"
    - "kubelet=1.9.7+nvidia"
    - "kubeadm=1.9.7+nvidia"
    - "cuda-drivers"

- name: Deploy daemon.json
  become: yes
  template:
    src: templates/daemon.json
    dest: /etc/docker/daemon.json
  register: daemonjson

- name: Restart docker
  become: yes
  service:
    name: docker
    state: restarted
    enabled: yes
  when: daemonjson.changed

