---
# This playbook cleans up all miners and removes all services

- name: Rancher agent launcher
  become: yes
  docker_container:
    name: rancher-agent-launcher
    image: rancher/agent:v1.2.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/rancher:/var/lib/rancher
    auto_remove: true
    privileged: true
    env:
      CATTLE_HOST_LABELS: "{{ rancher_labels|default(omit) }}"
    command: "{{ rancher[location] }}"
  register: rancheragent

- name: Display Rancher agent info
  debug:
    var: rancheragent
    verbosity: 4
