# Install AMD gpu and upgrade kernel

- name: Download AMD driver bundle
  become: yes
  unarchive:
    src: https://nexus.cowtownt.org/repository/mining-repo/amdgpu-pro/amdgpu-pro-18.50-708488-ubuntu-18.04.tar.xz
    dest: /var/tmp
    remote_src: yes
  register: downloadbundle

- name: Uninstall old AMD driver
  become: yes
  command: /usr/bin/amdgpu-pro-uninstall -y
  args:
    removes: /usr/bin/amdgpu-pro-uninstall
  when: downloadbundle.changed

- name: Check AMD driver install
  command: dpkg -l clinfo-amdgpu-pro
  register: clinfopackage
  ignore_errors: yes
  changed_when: no
  failed_when: false

- name: Install AMD driver bundle
  become: yes
  command: ./amdgpu-pro-install --opencl=legacy --headless --no-dkms -y
  when: clinfopackage.rc > 0
  args:
    chdir: /var/tmp/amdgpu-pro-18.50-708488-ubuntu-18.04

# Required to make above fully functional with Docker
- name: Install amdgpu-pro
  become: yes
  apt:
    name: amdgpu-pro
    
- name: Add wes to video group
  become: yes
  user:
    name: wes
    append: yes
    groups: video

- name: Upgrading kernel to support AMD GPU fast hashing
  become: yes
  apt:
    name: "{{ item }}"
  with_items:
    - linux-image-4.14.0-rc4-custom=4.14.0-rc4-custom-1
    - linux-headers-4.14.0-rc4-custom=4.14.0-rc4-custom-1
    - linux-libc-dev=4.14.0-rc4-custom-1
  when: ansible_distribution_version < 18.04

- name: Add kernel option for new linux kernel
  become: yes
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: 'GRUB_CMDLINE_LINUX="amdgpu.vm_fragment_size=9"'
  register: gruboptions1
  when: location == "weshouse"

- name: Add kernel option for new linux kernel
  become: yes
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: 'GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0 amdgpu.vm_fragment_size=9"'
  register: gruboptions2
  when: location == "jamiehouse"

- name: Update grub to pick up changes
  become: yes
  command: update-grub
  when: gruboptions1.changed or gruboptions2.changed

- name: Update initramfs
  become: yes
  command: update-initramfs -u
  when: gruboptions1.changed or gruboptions2.changed

